### ISSUE TITLE
계약관리 

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/MONOIssues#10]
![image](https://user-images.githubusercontent.com/16587438/74895134-42604900-53d4-11ea-9b53-eb14c3562bc9.png)

**Comment by jonghyunza** [comment]
1. 자동완성의 기능은 왼쪽의 메뉴 중 사용자관리에 상담직원을 등록 하였을 시에 나타나게 됩니다.
![image](https://user-images.githubusercontent.com/61259426/74909435-a77b6500-53fb-11ea-8e81-13b8ccf9ca91.png)

킹콩부대찌개 상에 한명의 상담사가 등록 되어 있으며
![image](https://user-images.githubusercontent.com/61259426/74909478-beba5280-53fb-11ea-9170-e4e143f6b433.png)

이렇게 등록 되게 되며 
상담직원으로 등록되지 않은 사람의 이름은 입력하여도 등록되지 않습니다.
