### ISSUE TITLE
사용자관리

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/MONOIssues#12]
![image](https://user-images.githubusercontent.com/16587438/74895256-82bfc700-53d4-11ea-8a25-0dad1b22be63.png)

**Comment by tpayGhs** [comment]
1. 주소검색버튼 추가하겠습니다.
2. 혹시 휴직은 사용자를 어떻게 사용하면 될까요??
- 현재는 재직여부 컬럼이 따로 없고, 삭제여부 컬럼과 삭제 일자 컬럼 2개만 있습니다.
3. 직급은 '기본사용자 그룹관리' 화면에서 입력합니다.
4. 사용여부 빼겠습니다.
