### ISSUE TITLE
생산품 판매현황 

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/MONOIssues#13]
![image](https://user-images.githubusercontent.com/16587438/74897375-42634780-53da-11ea-9868-030e65f14dce.png)
화면의 길이 자동 조정이 안되고 있습니다. 
화면을 늘리고 줄였을 경우 
그리드도 같이 조정 되게 부탁 드립니다.

**Comment by jonghyunza** [comment]
그리드 조절 이슈는 인지하고 있는 상태며 공통 모듈의 개발에 따른 추가 개발이 필요해 보입니다.
