### ISSUE TITLE
메뉴분류 / 시간대별 매출 조회

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/MONOIssues#16]
![image](https://user-images.githubusercontent.com/16587438/74903921-c70b9100-53ed-11ea-9be1-4d6bf780c345.png)

**Comment by kimsang5916** [comment]
대분류별 제외 버튼도 확인 부탁 드립니다. 
제외 누르면 암것도 조회 안되용 😢

**Comment by jonghyunza** [comment]
수정 완료 하였습니다.
