### ISSUE TITLE
업체관리

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/MONOIssues#4]
![image](https://user-images.githubusercontent.com/16587438/74893949-eb0ca980-53d0-11ea-9294-994306e5b03f.png)

**Comment by jonghyunza** [comment]
완료처리 하였습니다.
개발서버 상에는 반영이 되지 않았으며 
오늘 저녁에 자동 빌드가 되고 나면은 반영처리 될 것입니다.

**Comment by kimsang5916** [comment]
@jonghyunza 
👍 👍  확인 하였습니다. 
감사합니다.
