### ISSUE TITLE
매출내역조회 

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/MONOIssues#5]
![image](https://user-images.githubusercontent.com/16587438/74894559-ada91b80-53d2-11ea-8385-e47d6f4823cd.png)

매출내역 조회 화면의 
조회 내역이 주문내역으로 표기 됩니다. 
매출내역은 포스와 연동된 판매정보가 표기되는게 
맞는거 아닌지 확인 부탁 드립니다.

**Comment by jonghyunza** [comment]
매출내역조회와 생산품 판매현황은 POS와 연동되는 부분이 아니며 
MONO 상에서 수발주 내역에 관련된 내용이 나타나는 정보 화면입니다.

**Comment by kimsang5916** [comment]
@jonghyunza 
😢  네 ~ 감사합니다
