### ISSUE TITLE
[공통] 저장시 오류 메세지 표시 

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/MONOIssues#6]
![image](https://user-images.githubusercontent.com/16587438/74894976-c1a14d00-53d3-11ea-9894-dfcdc2b60255.png)

**Comment by jonghyunza** [comment]
내부적인 오류 메세지를 뿌려도 상관없는 부분일까요?
내부 로직 상에서 문제가 생겼을 경우 어떻게 처리 해야 하는지에 대한 논의가 필요해 보입니다.
