### ISSUE TITLE
개점상담관리 

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/MONOIssues#9]
![image](https://user-images.githubusercontent.com/16587438/74895082-180e8b80-53d4-11ea-996a-cf054d6e3fa3.png)

**Comment by tpayGhs** [comment]
우선 등록자는 실제 등록한 본인이 들어가게 되어있습니다, 
이유는 상담한 사람이 직접 작성을 한다는 전제가 있었습니다.
'등록자' 컴퍼넌트는 조회를 하기위한 부분 이였습니다.

위의 생각으로 화면을 구성한 것이었습니다. 
혹시 다르게 구성하고 싶으시면 다시 코멘트 달아주세요. 수정 하겠습니다.

**Comment by kimsang5916** [comment]
@jonghyunza 
네 이해했습니다.
우선 등록자 부분의 수정이 불가능하게 해주시고 
화면 처음 로딩시 등록자 부분의 로그인 한사람의 이름이 미리 셋팅되게  변경 부탁 드립니다.
